### ISSUE TITLE
SpookyGhost closes upon startup

### ISSUE THREAD

**Issue by Moxillian** [SpookyGhost2D/SpookyGhost#2] opened 2021-05-25 04:56 UTC
I am using SpookyGhost on Windows 8.1, when opening the program it closes instantly.

**Comment by encelo** [comment] 2021-05-25 08:55
Hi @Moxillian, and thanks for this report.

I have had issues with the versions compiled by GitHub Actions, the ones that you can find in the [SpookyGhost-master-windows-vs2017](https://github.com/SpookyGhost2D/SpookyGhost-artifacts/tree/SpookyGhost-master-windows-vs2017) and [SpookyGhost-master-windows-vs2019](https://github.com/SpookyGhost2D/SpookyGhost-artifacts/tree/SpookyGhost-master-windows-vs2019) branches of the `SpookyGhost-artifacts` project. Are you using any of those?

The Itch.io version had the same issue but later yesterday I uploaded a new build compiled on my machine and several testers confirmed it worked. Can you try this new build as well?

About the GitHub Actions compiled version I'm currently investigating the problem. :+1:

**Comment by encelo** [comment] 2021-06-02 23:54
The issue was caused by a missing CMake option on Windows and MinGW GitHub Actions workflows that caused the data not to be found and the program to gracefully exit on startup without showing any message.
It has now been fixed with the addition of the `-D PACKAGE_OPTIONS_PRESETS=${{ matrix.BuildType }}` option.

**Closed by encelo** 2021-06-02 23:54 UTC
